apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 2 # Number of replicas for the deployment [Scaling]
  strategy:
    type: RollingUpdate #[Rollout/Rollback]
  selector:
    matchLabels:
      app: preprocess # Label to match the pods. [self-healing]
  template:
    metadata:
      labels:
        app: preprocess
        env: tkb
    spec:
      containers:
      - name: preprocess
        image: yoshana/preprocessing-img:latest #need to replace the name with the docker hub username.
        ports:
        - containerPort: 5001 # Port on which the container listens
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe: # [SELF-HEALING]
          httpGet:
            path: /health 
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe: # [SELF-HEALING]
          httpGet:  
            path: /ready
            port: 5001
          initialDelaySeconds: 20
          periodSeconds: 5

