apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model-training
  template:
    metadata:
      labels:
        app: model-training
    spec:
      restartPolicy: Always
      containers:
      - name: training
        image: yoshana/training-model:latest
        imagePullPolicy: Always
        command: ["python", "train.py"]
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: training-data
          mountPath: /data
        - name: model-output
          mountPath: /data/saved_model
      volumes:
      - name: training-data
        hostPath:
          path: /path/on/host/data
      - name: model-output
        persistentVolumeClaim:
          claimName: model-pvc
 


        
      