apiVersion: apps/v1
kind: StatefulSet # postgres is stateful, so we use StatefulSet instead of Deployment
metadata:
  name: postgres 
spec:
  serviceName: postgres
  replicas: 3 
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: 'postgres:14'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        envFrom: # gets configs from configmap.yaml
            - configMapRef:
                name: postgres-secret 
        volumeMounts:
          - mountPath: /var/lib/postgresql/data # data written by postgres inside container here
            name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim: # from pvc.yaml
            claimName: postgres-volume-claim       

          