apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocess-deploy
spec:
  replicas: 3 # Number of replicas for the deployment [Scaling]
  strategy:
    type: RollingUpdate #[Rollout/Rollback]
  selector:
    matchLabels:
      app: preprocess # Label to match the pods. [self-healing]
  template:
    metadata:
      labels:
        app: preprocess
    spec:
      containers:
      - name: preprocess
        image: model/preprocess:latest #built an image with the preprocessing code
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe: # [SELF-HEALING]
          httpGet:
            path: /health 
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe: # [SELF-HEALING]
          httpGet:  
            path: /ready
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5