apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: wldkdnps/ui:latest # Replace with your built UI image
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: ui-config
        imagePullPolicy: IfNotPresent
